// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.LeituraAgregada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PrimeiroTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UltimoTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("UltimoValor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TalhaoId");

                    b.ToTable("LeituraAgregada", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RegraDeAlerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<bool>("ExigirJanelaCompleta")
                        .HasColumnType("bit");

                    b.Property<int>("JanelasConsecutivas")
                        .HasColumnType("int");

                    b.Property<double>("Limite")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RegraDeAlerta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Talhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Talhao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LeituraAgregada", b =>
                {
                    b.HasOne("Domain.Entities.Talhao", null)
                        .WithMany("Leituras")
                        .HasForeignKey("TalhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.TipoSensor", "Tipo", b1 =>
                        {
                            b1.Property<Guid>("LeituraAgregadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("Tipo");

                            b1.HasKey("LeituraAgregadaId");

                            b1.ToTable("LeituraAgregada");

                            b1.WithOwner()
                                .HasForeignKey("LeituraAgregadaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.EstatisticasAgregadas", "Estatisticas", b1 =>
                        {
                            b1.Property<Guid>("LeituraAgregadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Maxima")
                                .HasColumnType("float")
                                .HasColumnName("Maxima");

                            b1.Property<double>("Media")
                                .HasColumnType("float")
                                .HasColumnName("Media");

                            b1.Property<double>("Minima")
                                .HasColumnType("float")
                                .HasColumnName("Minima");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int")
                                .HasColumnName("Quantidade");

                            b1.Property<double>("Soma")
                                .HasColumnType("float")
                                .HasColumnName("Soma");

                            b1.HasKey("LeituraAgregadaId");

                            b1.ToTable("LeituraAgregada");

                            b1.WithOwner()
                                .HasForeignKey("LeituraAgregadaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Periodo", "Janela", b1 =>
                        {
                            b1.Property<Guid>("LeituraAgregadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Fim")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Fim");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Inicio");

                            b1.HasKey("LeituraAgregadaId");

                            b1.ToTable("LeituraAgregada");

                            b1.WithOwner()
                                .HasForeignKey("LeituraAgregadaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.UnidadeDeMedida", "Unidade", b1 =>
                        {
                            b1.Property<Guid>("LeituraAgregadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("Unidade");

                            b1.HasKey("LeituraAgregadaId");

                            b1.ToTable("LeituraAgregada");

                            b1.WithOwner()
                                .HasForeignKey("LeituraAgregadaId");
                        });

                    b.Navigation("Estatisticas")
                        .IsRequired();

                    b.Navigation("Janela")
                        .IsRequired();

                    b.Navigation("Tipo")
                        .IsRequired();

                    b.Navigation("Unidade")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RegraDeAlerta", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.TipoSensor", "Tipo", b1 =>
                        {
                            b1.Property<Guid>("RegraDeAlertaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("Tipo");

                            b1.HasKey("RegraDeAlertaId");

                            b1.ToTable("RegraDeAlerta");

                            b1.WithOwner()
                                .HasForeignKey("RegraDeAlertaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.EstatisticaAlvo", "Alvo", b1 =>
                        {
                            b1.Property<Guid>("RegraDeAlertaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("Alvo");

                            b1.HasKey("RegraDeAlertaId");

                            b1.ToTable("RegraDeAlerta");

                            b1.WithOwner()
                                .HasForeignKey("RegraDeAlertaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.OperadorComparacao", "Operador", b1 =>
                        {
                            b1.Property<Guid>("RegraDeAlertaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Operador");

                            b1.HasKey("RegraDeAlertaId");

                            b1.ToTable("RegraDeAlerta");

                            b1.WithOwner()
                                .HasForeignKey("RegraDeAlertaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Severidade", "Severidade", b1 =>
                        {
                            b1.Property<Guid>("RegraDeAlertaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("Severidade");

                            b1.HasKey("RegraDeAlertaId");

                            b1.ToTable("RegraDeAlerta");

                            b1.WithOwner()
                                .HasForeignKey("RegraDeAlertaId");
                        });

                    b.Navigation("Alvo")
                        .IsRequired();

                    b.Navigation("Operador")
                        .IsRequired();

                    b.Navigation("Severidade")
                        .IsRequired();

                    b.Navigation("Tipo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Talhao", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
